	.ORIG x3000
	
	AND R2,R2,#0	;CLEAR R2
	LD R0, Q1	;LOAD Q1
	PUTS		;PRINT IT
	JSR GET_ANSW	;JUMP TO SUBROUTINE 
	LD R1, Q1_ANSW
	JSR GET_PNTS
		

	LD R0, Q2	;LOAD Q2
	PUTS		;PRINT IT
	JSR GET_ANSW	;SUB
	LD R1,Q2_ANSW
	JSR GET_PNTS

	LD R0, Q3	;LOAD Q3
	PUTS		;PRINT
	JSR GET_ANSW	;SUB
	LD R1,Q3_ANSW
	JSR GET_PNTS

	;HERE I WOULD PRINT RESULTS

	HALT

Q1	.FILL x3300
Q1_ANSW	.FILL x3357
Q2	.FILL x335B
Q2_ANSW	.FILL x33BB
Q3	.FILL x33BF
Q3_ANSW	.FILL x3442

ANSW	.STRINGZ "Answer: "
RS_1	.FILL x3446

SAVE_R0	.FILL #0
SAVE_R1	.FILL #0
SAVE_R7	.FILL #0
SAVE_R72	.FILL #0
ASCII	.FILL x-30

;========GET ANSWER============
;
;
GET_ANSW

	ST R1, SAVE_R1	;SAVE R1
	ST R7, SAVE_R7	;SAVE R7
	
	GETC		;GET THE CHARACTER
	ST R0, SAVE_R0	;SAVE R0

	JSR PRINT	;PRINT ANSWER	

	
	LD R1, ASCII	;LOAD #-30 INTO R1
	ADD R0,R0,R1	;MAKE R0 THE ACTUAL NUMBER
	
	;JSR GET_PNTS	;SUBROUTINE FOR POINTS

	LD R7, SAVE_R7
	LD R1, SAVE_R1
	RET


;==========GET POINTS====================
;
;
GET_PNTS
	
	ADD R0,R0,#-1	;ADD -1 TO ANSWER TO GET THE LOCATION RIGHT
	

	;LD R1, Q1_ANSW	;LOAD ADRESS OF SCORE
	ADD R1,R0,R1	;ADD THE # TO GET RIGHT SCORE
	
	LDR R3,R1,#0	;KEEP SCORE IN R3!
	ADD R2,R2,R3	;RUNNING SCORE
	ADD R0,R0,#1	;ADD 1 TO GET ORIGINAL ANSWER	

        RET

;==========PRINT=============
PRINT	LEA R0,ANSW
	ST R7, SAVE_R72
	PUTS
	LD R0,SAVE_R0

	OUT
	LD R7, SAVE_R72
	RET
	
	.END

	
